//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR7
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarehouseItems
    {
        public int WarehouseItemID { get; set; }
        public int PartTypeID { get; set; }
        public int Quantity { get; set; }
    
        public virtual PartTypes PartTypes { get; set; }
    }
}
